In [51]:
import tensorflow as tf 
# WARNING:tensorflow:From c:\Users\Daivik\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead

Data types

In [52]:
string = tf.Variable("Daivik", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.1456, tf.float16)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1456>


Rank or Degree

In [53]:
rank1 = tf.Variable(["test", "ok"],tf.string)
rank2 = tf.Variable([[1,2],[1,3]])
print(rank1)
print(rank2)
# very imp that the list should have same length within the same tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'test', b'ok'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [1, 3]])>


In [54]:
tf.rank(rank1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

shape

In [55]:
rank3 = tf.Variable([[[[[1],[1]]]]])
print(rank1.shape)
print(rank2.shape)
print(rank3.shape)

(2,)
(2, 2)
(1, 1, 1, 2, 1)


changing shape

In [56]:
tensor1 = tf.ones([1,2,3])
print(tensor1,"/n")
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2, "/n")
tensor3 = tf.reshape(tensor1, [3,-1])
print(tensor3, "/n")

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32) /n
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) /n
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) /n


Types of tensors 
<li> Variable
<li> Constant
<li> Placeholder
<li> SparseTensor

Evaluate a tensor (this method  is  removed in TenforFlow 2.x)

In [57]:
# with tf.Session() as sess:
#   tensor1.eval()

In [58]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\Daivik\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>
